<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="6" total="13" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="ActiTime_Suite" duration-ms="54728" started-at="2022-06-24T08:19:58 IST" finished-at="2022-06-24T08:20:53 IST">
    <groups>
      <group name="Sanity">
        <method signature="Reports.report()[pri:0, instance:reports.Reports@59e5ddf]" name="report" class="reports.Reports"/>
      </group> <!-- Sanity -->
      <group name="Regression">
        <method signature="CommonTest.login_ActiTime()[pri:0, instance:common_tests.CommonTest@1b68ddbd]" name="login_ActiTime" class="common_tests.CommonTest"/>
        <method signature="CreateCustomer.createTasks(java.lang.String)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="createTasks" class="enter_TimeTrack.CreateCustomer"/>
        <method signature="Reports.report()[pri:0, instance:reports.Reports@59e5ddf]" name="report" class="reports.Reports"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="CreateCustomer.createTasks(java.lang.String)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="createTasks" class="enter_TimeTrack.CreateCustomer"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Test1" duration-ms="54728" started-at="2022-06-24T08:19:58 IST" finished-at="2022-06-24T08:20:53 IST">
      <class name="reports.Reports">
        <test-method status="PASS" signature="setUpTestCase(java.lang.reflect.Method)[pri:0, instance:reports.Reports@59e5ddf]" name="setUpTestCase" is-config="true" duration-ms="0" started-at="2022-06-24T08:20:36 IST" finished-at="2022-06-24T08:20:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void reports.Reports.report() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method status="FAIL" signature="report()[pri:0, instance:reports.Reports@59e5ddf]" name="report" duration-ms="16783" started-at="2022-06-24T08:20:36 IST" finished-at="2022-06-24T08:20:53 IST">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[no such element: Unable to locate element: {"method":"xpath","selector":"//div//div[@class='containers-CustomFieldsReport-title--2v110BXG' and contains(text(), 'Custom Fields Report')]"}
  (Session info: chrome=103.0.5060.53)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-IN3O14F1', ip: '192.168.1.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_311'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.53, chrome: {chromedriverVersion: 102.0.5005.61 (0e59bcc00cc4..., userDataDir: C:\Users\uniqu\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:64951}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f33d00558e8768b0abca1c5c7d94ffc5
*** Element info: {Using=xpath, value=//div//div[@class='containers-CustomFieldsReport-title--2v110BXG' and contains(text(), 'Custom Fields Report')]}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div//div[@class='containers-CustomFieldsReport-title--2v110BXG' and contains(text(), 'Custom Fields Report')]"}
  (Session info: chrome=103.0.5060.53)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-IN3O14F1', ip: '192.168.1.9', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_311'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.53, chrome: {chromedriverVersion: 102.0.5005.61 (0e59bcc00cc4..., userDataDir: C:\Users\uniqu\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:64951}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: f33d00558e8768b0abca1c5c7d94ffc5
*** Element info: {Using=xpath, value=//div//div[@class='containers-CustomFieldsReport-title--2v110BXG' and contains(text(), 'Custom Fields Report')]}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at reports.Reports.report(Reports.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
      </class> <!-- reports.Reports -->
      <class name="common_tests.CommonTest">
        <test-method status="PASS" signature="initialSetUp()[pri:0, instance:common_tests.CommonTest@1b68ddbd]" name="initialSetUp" is-config="true" duration-ms="7442" started-at="2022-06-24T08:19:51 IST" finished-at="2022-06-24T08:19:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:common_tests.CommonTest@1b68ddbd]" name="setUp" is-config="true" duration-ms="25" started-at="2022-06-24T08:19:58 IST" finished-at="2022-06-24T08:19:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUpTestCase(java.lang.reflect.Method)[pri:0, instance:common_tests.CommonTest@1b68ddbd]" name="setUpTestCase" is-config="true" duration-ms="9" started-at="2022-06-24T08:19:58 IST" finished-at="2022-06-24T08:19:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void common_tests.CommonTest.login_ActiTime() throws java.lang.InterruptedException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method status="FAIL" signature="login_ActiTime()[pri:0, instance:common_tests.CommonTest@1b68ddbd]" name="login_ActiTime" duration-ms="6679" started-at="2022-06-24T08:19:58 IST" finished-at="2022-06-24T08:20:05 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Enter Time-Track for] but found [Enter Time-Track fo r]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Enter Time-Track for] but found [Enter Time-Track fo r]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at common_tests.CommonTest.login_ActiTime(CommonTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_ActiTime -->
        <test-method status="PASS" signature="closeConnection()[pri:0, instance:common_tests.CommonTest@1b68ddbd]" name="closeConnection" is-config="true" duration-ms="6042" started-at="2022-06-24T08:20:53 IST" finished-at="2022-06-24T08:20:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeConnection -->
      </class> <!-- common_tests.CommonTest -->
      <class name="enter_TimeTrack.CreateCustomer">
        <test-method status="PASS" signature="be_in_Tasks()[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="be_in_Tasks" is-config="true" duration-ms="1912" started-at="2022-06-24T08:20:05 IST" finished-at="2022-06-24T08:20:07 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- be_in_Tasks -->
        <test-method status="PASS" signature="setUpTestCase(java.lang.reflect.Method)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="setUpTestCase" is-config="true" duration-ms="0" started-at="2022-06-24T08:20:07 IST" finished-at="2022-06-24T08:20:07 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void enter_TimeTrack.CreateCustomer.createTasks(java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method status="PASS" signature="createTasks(java.lang.String)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="createTasks" duration-ms="6148" started-at="2022-06-24T08:20:07 IST" data-provider="createTask" finished-at="2022-06-24T08:20:13 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Task_1_]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTasks -->
        <test-method status="PASS" signature="setUpTestCase(java.lang.reflect.Method)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="setUpTestCase" is-config="true" duration-ms="0" started-at="2022-06-24T08:20:13 IST" finished-at="2022-06-24T08:20:13 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void enter_TimeTrack.CreateCustomer.createTasks(java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method status="PASS" signature="createTasks(java.lang.String)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="createTasks" duration-ms="5803" started-at="2022-06-24T08:20:13 IST" data-provider="createTask" finished-at="2022-06-24T08:20:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Task_2_]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTasks -->
        <test-method status="PASS" signature="setUpTestCase(java.lang.reflect.Method)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="setUpTestCase" is-config="true" duration-ms="1" started-at="2022-06-24T08:20:19 IST" finished-at="2022-06-24T08:20:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void enter_TimeTrack.CreateCustomer.createTasks(java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method status="PASS" signature="createTasks(java.lang.String)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="createTasks" duration-ms="5818" started-at="2022-06-24T08:20:19 IST" data-provider="createTask" finished-at="2022-06-24T08:20:25 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Task_3_]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTasks -->
        <test-method status="PASS" signature="setUpTestCase(java.lang.reflect.Method)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="setUpTestCase" is-config="true" duration-ms="1" started-at="2022-06-24T08:20:25 IST" finished-at="2022-06-24T08:20:25 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void enter_TimeTrack.CreateCustomer.createTasks(java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method status="PASS" signature="createTasks(java.lang.String)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="createTasks" duration-ms="5444" started-at="2022-06-24T08:20:25 IST" data-provider="createTask" finished-at="2022-06-24T08:20:30 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Task_4_]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTasks -->
        <test-method status="PASS" signature="setUpTestCase(java.lang.reflect.Method)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="setUpTestCase" is-config="true" duration-ms="1" started-at="2022-06-24T08:20:30 IST" finished-at="2022-06-24T08:20:30 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void enter_TimeTrack.CreateCustomer.createTasks(java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTestCase -->
        <test-method status="PASS" signature="createTasks(java.lang.String)[pri:0, instance:enter_TimeTrack.CreateCustomer@646d64ab]" name="createTasks" duration-ms="5459" started-at="2022-06-24T08:20:30 IST" data-provider="createTask" finished-at="2022-06-24T08:20:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Task_5_]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createTasks -->
      </class> <!-- enter_TimeTrack.CreateCustomer -->
    </test> <!-- Test1 -->
  </suite> <!-- ActiTime_Suite -->
</testng-results>
